title: Learning Lab Blog
author: LordOfCats4080
email: lordofcats4080@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a Learning Lab blog.
theme: minima

# social links
twitter_username: LordOfCats6 # DO NOT include the @ character, or else the build will fail!
github_username:  LordOfCats4080 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
